FROM python:3.10.6-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY frontend.py frontend.py

CMD streamlit run frontend.py --server.address=0.0.0.0 --server.port=${PORT:-8501}
