"""
This file contains all functions required to interact with the Gemni LLM and retrieve the
commentary on the results for the predicted statement, based on:
- Statement to be predicted
- Prediction results
- Similar statements to predicted statement, retrieved from vector store
- Prompt created by prompt_creator function
"""

from langchain_google_genai import ChatGoogleGenerativeAI
from IPython.display import Markdown
from langsmith import Client

def prompt_creator(X_predict, final_prediction, df_retrieved, max_words=100):
    """"
    This function takes:
    - Statement to be predicted (with speaker and context information).
    - Prediction object out of the models for the predicted statement.
    - Similar statements retrieved from the vectror store
    And generates a prompt that will be sent to the LLM in order to get qualitative information on the prediction scores.
    """

    # We define main context for the query (System message)

    system_msg = """
    You are a political fact-checking assistant.
    Use the "retrieved examples" to explain the prediction.
    Do not invent facts.
    Base your reasoning on the provided examples.
    Only three labels are possible (Unreliable, Questionable, Trustworthy)
    """

    # We retrieve all information from statement to evaluate

    q_statement = X_predict["statement"]                 # Retrieve statement to evaluate
    q_speaker = X_predict["speaker"]                     # Retrieve speaker that made the statement
    q_context = X_predict["context"]                     # Retrieve context about the statement


    # We retrieve all information predicted by models about the statement

    q_prediction_nb = final_prediction["pred_nb"]        # Retrieve prediction from Naive Bayes model
    q_probas_nb = final_prediction["probas_nb"]          # Retrieve confidence from Naive Bayes model
    q_prediction_xg = final_prediction["pred_xgb"]       # Retrieve prediction from NB + XG_Boost models
    q_probas_xg = final_prediction["probas_xgb"]        # Retrieve confidence from NB + XG_Boost models


    # We retrieve top k similar statements stored in Chroma

    q_similar_st2 = "\n\n".join(
        df_retrieved.head(3).apply(
            lambda row:
            f"Label: {row['label']}\n"
            f"Speaker: {row['speaker']}\n"
            f"Context: {row['context']}\n"
            f"Statement: {row['statement']}",
            axis=1
        )
    )

    human_msg = f"""
    Statement to evaluate: {q_statement}\n
    Speaker: {q_speaker}\n
    Context: {q_context}\n\n
    Naive Bayes prediction: {q_prediction_nb}\n
    XG_Boost prediction: {q_prediction_xg}\n\n
    Retrieved similar statements from training dataset:\n
    {q_similar_st2}\n\n
    Explain in maximum {max_words} words:\n
    - What patterns appear in the retrieved examples \n
    - Possible rethorical bias
    """

    messages = [system_msg, human_msg]

    return messages



def llm_query(temperature, max_tokens, messages):
    """
    This function takes:
    - Prompt generated by prompt_creator
    - Temperature
    - Max_tokens
    And generates an answer by the Gemini LLM to be displayed, explaining possible reasonings behind the scores, rethorics etc...
    """

    llm_model = ChatGoogleGenerativeAI(
        model="gemini-2.5-flash",
        temperature=temperature,
        max_tokens=max_tokens
    )

    client = Client()

    response = llm_model.invoke(messages)

    return Markdown(response.text)
